=== eduardoschwartz/GTI_v3C/GTI_Desktop/Datasets/Detalhe_Parcela.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" >
  <xsd:element name="Detalhe_Parcela">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Codigo" type="xsd:int"></xsd:element>
        <xsd:element name="Nome" type="xsd:string"></xsd:element>
        <xsd:element name="Exercicio" type="xsd:int"></xsd:element>
        <xsd:element name="Lanc" type="xsd:int"></xsd:element>
        <xsd:element name="Lancamento" type="xsd:string"></xsd:element>
        <xsd:element name="Seq" type="xsd:int"></xsd:element>
        <xsd:element name="Parc" type="xsd:int"></xsd:element>
        <xsd:element name="Compl" type="xsd:int"></xsd:element>
        <xsd:element name="Status" type="xsd:string"></xsd:element>
        <xsd:element name="Isento" type="xsd:string"></xsd:element>
        <xsd:element name="Desconto" type="xsd:string"></xsd:element>
        <xsd:element name="Livro" type="xsd:string"></xsd:element>
        <xsd:element name="Data_Inscricao" type="xsd:string"></xsd:element>
        <xsd:element name="Pagina" type="xsd:string"></xsd:element>
        <xsd:element name="Certidao" type="xsd:string"></xsd:element>
        <xsd:element name="Data_Ajuiza" type="xsd:string"></xsd:element>
        <xsd:element name="ProcessoCnj" type="xsd:string"></xsd:element>
        <xsd:element name="Protocolo" type="xsd:string"></xsd:element>
        <xsd:element name="Data_Remessa" type="xsd:string"></xsd:element>
        <xsd:element name="Data_Base" type="xsd:string"></xsd:element>
        <xsd:element name="Data_Vencto" type="xsd:string"></xsd:element>
        <xsd:element name="Data_VenctoCalc" type="xsd:string"></xsd:element>
        <xsd:element name="Data_Pagamento" type="xsd:string"></xsd:element>
        <xsd:element name="Data_Receita" type="xsd:string"></xsd:element>
        <xsd:element name="Valor_Lancado" type="xsd:decimal"></xsd:element>
        <xsd:element name="Valor_Atual" type="xsd:decimal"></xsd:element>
        <xsd:element name="Valor_Pago" type="xsd:decimal"></xsd:element>
        <xsd:element name="Valor_Dif" type="xsd:decimal"></xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== eduardoschwartz/GTI_v3C/GTI_Desktop/Datasets/Detalhe_Parcela.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<Detalhe_Parcela xsi:noNamespaceSchemaLocation="Detalhe_Parcela.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Codigo>3610</Codigo>
  <Nome>string</Nome>
  <Exercicio>-986</Exercicio>
  <Lanc>1</Lanc>
  <Lancamento>string</Lancamento>
  <Seq>4129</Seq>
  <Parc>-3063</Parc>
  <Compl>1784</Compl>
  <Status>string</Status>
  <Isento>string</Isento>
  <Desconto>string</Desconto>
  <Livro>string</Livro>
  <Data_Inscricao>string</Data_Inscricao>
  <Pagina>string</Pagina>
  <Certidao>string</Certidao>
  <Data_Ajuiza>string</Data_Ajuiza>
  <ProcessoCnj>string</ProcessoCnj>
  <Protocolo>string</Protocolo>
  <Data_Remessa>string</Data_Remessa>
  <Data_Base>string</Data_Base>
  <Data_Vencto>string</Data_Vencto>
  <Data_VenctoCalc>string</Data_VenctoCalc>
  <Data_Pagamento>string</Data_Pagamento>
  <Data_Receita>string</Data_Receita>
  <Valor_Lancado>161880.234905804</Valor_Lancado>
  <Valor_Atual>3337730.2349058</Valor_Atual>
  <Valor_Pago>-2976989.7650942</Valor_Pago>
  <Valor_Dif>-4629649.7650942</Valor_Dif>
  <Banco>string</Banco>
</Detalhe_Parcela>
