=== eduardoschwartz/GTI_v3C/GTI_Desktop/Datasets/Detalhe_Parcela_Tributo.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" >
  <xsd:element name="Detalhe_Parcela_Tributo">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Codigo" type="xsd:int"></xsd:element>
        <xsd:element name="Exercicio" type="xsd:int"></xsd:element>
        <xsd:element name="Lanc" type="xsd:int"></xsd:element>
        <xsd:element name="Seq" type="xsd:int"></xsd:element>
        <xsd:element name="Parc" type="xsd:int"></xsd:element>
        <xsd:element name="Compl" type="xsd:int"></xsd:element>
        <xsd:element name="Codtributo" type="xsd:int"></xsd:element>
        <xsd:element name="Desctributo" type="xsd:string"></xsd:element>
        <xsd:element name="Principal" type="xsd:decimal"></xsd:element>
        <xsd:element name="Juros" type="xsd:decimal"></xsd:element>
        <xsd:element name="Multa" type="xsd:decimal"></xsd:element>
        <xsd:element name="Correcao" type="xsd:decimal"></xsd:element>
        <xsd:element name="Total" type="xsd:decimal"></xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== eduardoschwartz/GTI_v3C/GTI_Desktop/Datasets/Detalhe_Parcela_Tributo.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<Detalhe_Parcela_Tributo xsi:noNamespaceSchemaLocation="Detalhe_Parcela_Tributo.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Codigo>762</Codigo>
  <Exercicio>-2065</Exercicio>
  <Lanc>3848</Lanc>
  <Seq>-1795</Seq>
  <Parc>-1569</Parc>
  <Compl>-355</Compl>
  <Codtributo>4208</Codtributo>
  <Desctributo>string</Desctributo>
  <Principal>-3178919.7650942</Principal>
  <Juros>-4351909.7650942</Juros>
  <Multa>1379140.2349058</Multa>
  <Correcao>1961390.2349058</Correcao>
  <Total>3678350.2349058</Total>
</Detalhe_Parcela_Tributo>
