=== eduardoschwartz/GTI_v3C/GTI_WebCore/Models/ReportModels/Certidao.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" >
  <!-- XML Schema Generated from XML Document on Tue Aug 13 2019 14:13:53 GMT-0300 (Horário Padrão de Brasília) -->
  <!-- with XmlGrid.net Free Online Service http://xmlgrid.net -->
  <xsd:element name="Certidao">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Codigo" type="xsd:int"></xsd:element>
        <xsd:element name="Ano" type="xsd:int"></xsd:element>
        <xsd:element name="Numero" type="xsd:int"></xsd:element>
        <xsd:element name="Numero_Ano" type="xsd:string"></xsd:element>
        <xsd:element name="Inscricao" type="xsd:string"></xsd:element>
        <xsd:element name="Nome_Requerente" type="xsd:string"></xsd:element>
        <xsd:element name="Endereco" type="xsd:string"></xsd:element>
        <xsd:element name="Endereco_Numero" type="xsd:int"></xsd:element>
        <xsd:element name="Endereco_Complemento" type="xsd:string"></xsd:element>
        <xsd:element name="Bairro" type="xsd:string"></xsd:element>
        <xsd:element name="Quadra_Original" type="xsd:string"></xsd:element>
        <xsd:element name="Lote_Original" type="xsd:string"></xsd:element>
        <xsd:element name="Controle" type="xsd:string"></xsd:element>
        <xsd:element name="Data_Geracao" type="xsd:dateTime"></xsd:element>
        <xsd:element name="Area" type="xsd:decimal"></xsd:element>
        <xsd:element name="VVT" type="xsd:decimal"></xsd:element>
        <xsd:element name="VVP" type="xsd:decimal"></xsd:element>
        <xsd:element name="VVI" type="xsd:decimal"></xsd:element>
        <xsd:element name="Numero_Processo" type="xsd:string"></xsd:element>
        <xsd:element name="Data_Processo" type="xsd:dateTime"></xsd:element>
        <xsd:element name="Percentual_Isencao" type="xsd:decimal"></xsd:element>
        <xsd:element name="Insc_Estadual" type="xsd:string"></xsd:element>
        <xsd:element name="Data_Abertura" type="xsd:dateTime"></xsd:element>
        <xsd:element name="Data_Encerramento" type="xsd:dateTime"></xsd:element>
        <xsd:element name="Processo_Abertura" type="xsd:string"></xsd:element>
        <xsd:element name="Processo_Encerramento" type="xsd:string"></xsd:element>
        <xsd:element name="Cpf_Cnpj" type="xsd:string"></xsd:element>
        <xsd:element name="Razao_Social" type="xsd:string"></xsd:element>
        <xsd:element name="Nome_Fantasia" type="xsd:string"></xsd:element>
        <xsd:element name="Atividade_Extenso" type="xsd:string"></xsd:element>
        <xsd:element name="Cnae_Principal" type="xsd:string"></xsd:element>
        <xsd:element name="Cnae_Secundario" type="xsd:string"></xsd:element>
        <xsd:element name="Rg" type="xsd:string"></xsd:element>
        <xsd:element name="Cidade" type="xsd:string"></xsd:element>
        <xsd:element name="uf" type="xsd:string"></xsd:element>
        <xsd:element name="Exercicio" type="xsd:short"></xsd:element>
        <xsd:element name="Lancamento_codigo" type="xsd:byte"></xsd:element>
        <xsd:element name="Lancamento_nome" type="xsd:string"></xsd:element>
        <xsd:element name="Sequencia_Lancamento" type="xsd:byte"></xsd:element>
        <xsd:element name="Parcela" type="xsd:byte"></xsd:element>
        <xsd:element name="Complemento" type="xsd:byte"></xsd:element>
        <xsd:element name="Data_Vencimento" type="xsd:dateTime"></xsd:element>
        <xsd:element name="Data_Pagamento" type="xsd:dateTime"></xsd:element>
        <xsd:element name="Valor_Pago" type="xsd:decimal"></xsd:element>
        <xsd:element name="Tipo_Certidao" type="xsd:string"></xsd:element>
        <xsd:element name="Nao" type="xsd:string"></xsd:element>
        <xsd:element name="Certifica" type="xsd:string"></xsd:element>
        <xsd:element name="Tributo" type="xsd:string"></xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== eduardoschwartz/GTI_v3C/GTI_WebCore/Models/ReportModels/Certidao.xml
<Certidao  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="Certidao.xsd">
  <Codigo>123456</Codigo>
  <Ano>2000</Ano>
  <Numero>35</Numero>
  <Numero_Ano>35/2000</Numero_Ano>
  <Inscricao>'1.03.0005.01234.45'</Inscricao>
  <Nome_Requerente>'Eduardo Schwartz'</Nome_Requerente>
  <Endereco>'Rua 1'</Endereco>
  <Endereco_Numero>25</Endereco_Numero>
  <Endereco_Complemento>Fundos</Endereco_Complemento>
  <Bairro>'Centro'</Bairro>
  <Quadra_Original>'2A'</Quadra_Original>
  <Lote_Original>'3B'</Lote_Original>
  <Controle>'ABC123'</Controle>
  <Data_Geracao>1980-03-23T10:20:15</Data_Geracao>
  <Area>25.65</Area>
  <VVT>132.58</VVT>
  <VVP>146.96</VVP>
  <VVI>321.56</VVI>
  <Numero_Processo>'35'</Numero_Processo>
  <Data_Processo>1980-03-23T10:20:15</Data_Processo>
  <Percentual_Isencao>32.1</Percentual_Isencao>
  <Insc_Estadual>1</Insc_Estadual>
  <Data_Abertura>1980-03-23T10:20:15</Data_Abertura>
  <Data_Encerramento>1980-03-23T10:20:15</Data_Encerramento>
  <Processo_Abertura>35/2005</Processo_Abertura>
  <Processo_Encerramento>1980-03-23T10:20:15</Processo_Encerramento>
  <Cpf_Cnpj>65678</Cpf_Cnpj>
  <Razao_Social>yuuyu</Razao_Social>
  <Nome_Fantasia>hjgjh></Nome_Fantasia>
  <Atividade_Extenso>hgh</Atividade_Extenso>
  <Cnae_Principal>8787</Cnae_Principal>
  <Cnae_Secundario>7676</Cnae_Secundario>
  <Rg>222</Rg>
  <Cidade>Jaboticabal</Cidade>
  <uf>SP</uf>
  <Exercicio>2010</Exercicio>
  <Lancamento_codigo>1</Lancamento_codigo>
  <Lancamento_nome>aa</Lancamento_nome>
  <Sequencia_Lancamento>2</Sequencia_Lancamento>
  <Parcela>2</Parcela>
  <Complemento>1</Complemento>
  <Data_Vencimento>1980-03-23T10:20:15</Data_Vencimento>
  <Data_Pagamento>1980-03-23T10:20:15</Data_Pagamento>
  <Valor_Pago>22</Valor_Pago>
  <Tipo_Certidao>Positiva</Tipo_Certidao>
  <Nao>Sim</Nao>
  <Certifica>que</Certifica>
  <Tributo>IPTU</Tributo>
</Certidao>
