=== eduardoschwartz/GTI_v3C/GTI_WebCore/Models/ReportModels/Comprovante_Inscricao.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <!-- XML Schema Generated from XML Document on Sun Aug 18 2019 19:59:34 GMT-0300 (Horário Padrão de Brasília) -->
  <!-- with XmlGrid.net Free Online Service http://xmlgrid.net -->
  <xs:element name="Comprovante_Inscricao">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Numero" type="xs:int"></xs:element>
        <xs:element name="Ano" type="xs:int"></xs:element>
        <xs:element name="Data_Emissao" type="xs:dateTime"></xs:element>
        <xs:element name="Controle" type="xs:string"></xs:element>
        <xs:element name="Endereco" type="xs:string"></xs:element>
        <xs:element name="Codigo" type="xs:int"></xs:element>
        <xs:element name="Razao_Social" type="xs:string"></xs:element>
        <xs:element name="Bairro" type="xs:string"></xs:element>
        <xs:element name="Cidade" type="xs:string"></xs:element>
        <xs:element name="UF" type="xs:string"></xs:element>
        <xs:element name="Cpf_Cnpj" type="xs:string"></xs:element>
        <xs:element name="Atividade" type="xs:string"></xs:element>
        <xs:element name="Data_Abertura" type="xs:dateTime"></xs:element>
        <xs:element name="Inscricao_Estadual" type="xs:int"></xs:element>
        <xs:element name="Nome_Fantasia" type="xs:string"></xs:element>
        <xs:element name="Cep" type="xs:int"></xs:element>
        <xs:element name="Atividade2" type="xs:string"></xs:element>
        <xs:element name="Complemento" type="xs:string"></xs:element>
        <xs:element name="Situacao" type="xs:string"></xs:element>
        <xs:element name="Email" type="xs:string"></xs:element>
        <xs:element name="Telefone" type="xs:string"></xs:element>
        <xs:element name="Taxa_Licenca" type="xs:string"></xs:element>
        <xs:element name="Vigilancia_Sanitaria" type="xs:string"></xs:element>
        <xs:element name="Mei" type="xs:string"></xs:element>
        <xs:element name="Area" type="xs:string"></xs:element>
        <xs:element name="Rg" type="xs:int"></xs:element>
        <xs:element name="Processo_Abertura" type="xs:string"></xs:element>
        <xs:element name="Processo_Encerramento" type="xs:string"></xs:element>
        <xs:element name="Data_Encerramento" type="xs:dateTime"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== eduardoschwartz/GTI_v3C/GTI_WebCore/Models/ReportModels/Comprovante_Inscricao.xml
<Comprovante_Inscricao xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="Comprovante_Inscricao.xsd">
  <Numero>35</Numero>
  <Ano>2000</Ano>
  <Data_Emissao>1980-03-23T10:20:15</Data_Emissao>
  <Controle>'12121'</Controle>
  <Endereco>Rua de Teste, 345 - 2ª Andar</Endereco>
  <Codigo>123456</Codigo>
  <Razao_Social>Empresa de Teste</Razao_Social>
  <Bairro>Nova Cidade</Bairro>
  <Cidade>Jaboticabal</Cidade>
  <UF>SP</UF>
  <Cpf_Cnpj>50.387.655/0002-23</Cpf_Cnpj>
  <Atividade>Mecânico</Atividade>
  <Data_Abertura>1980-03-23T10:20:15</Data_Abertura>
  <Inscricao_Estadual>12121</Inscricao_Estadual>
  <Nome_Fantasia>sss</Nome_Fantasia>
  <Cep>15990450</Cep>
  <Atividade2>jdksldj</Atividade2>
  <Complemento>sala 1</Complemento>
  <Situacao>Ativa</Situacao>
  <Email>email@gti.com</Email>
  <Telefone>(16) 3333-2222</Telefone>
  <Taxa_Licenca>Sim</Taxa_Licenca>
  <Vigilancia_Sanitaria>Não</Vigilancia_Sanitaria>
  <Mei>Sim</Mei>
  <Area>1234,56 m²</Area>
  <Rg>9898</Rg>
  <Processo_Abertura>53/2010</Processo_Abertura>
  <Processo_Encerramento>53/2010</Processo_Encerramento>
  <Data_Encerramento>1980-03-23T10:20:15</Data_Encerramento>
</Comprovante_Inscricao>
