=== eduardoschwartz/GTI_v3C/GTI_WebCore/Models/ReportModels/Empresa_Detalhe.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <!-- XML Schema Generated from XML Document on Wed Aug 14 2019 14:27:00 GMT-0300 (Horário Padrão de Brasília) -->
  <!-- with XmlGrid.net Free Online Service http://xmlgrid.net -->
  <xs:element name="Empresa_Detalhe">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Codigo" type="xs:int"></xs:element>
        <xs:element name="Razao_Social" type="xs:string"></xs:element>
        <xs:element name="Cpf_Cnpj" type="xs:string"></xs:element>
        <xs:element name="Inscricao_Estadual" type="xs:int"></xs:element>
        <xs:element name="Endereco" type="xs:string"></xs:element>
        <xs:element name="Bairro" type="xs:string"></xs:element>
        <xs:element name="Cidade" type="xs:string"></xs:element>
        <xs:element name="UF" type="xs:string"></xs:element>
        <xs:element name="Cep" type="xs:int"></xs:element>
        <xs:element name="Data_Abertura" type="xs:dateTime"></xs:element>
        <xs:element name="Data_Encerramento" type="xs:dateTime"></xs:element>
        <xs:element name="Atividade" type="xs:string"></xs:element>
        <xs:element name="Situacao" type="xs:string"></xs:element>
        <xs:element name="Email" type="xs:string"></xs:element>
        <xs:element name="Telefone" type="xs:string"></xs:element>
        <xs:element name="RegimeISS" type="xs:string"></xs:element>
        <xs:element name="Taxa_Licenca" type="xs:string"></xs:element>
        <xs:element name="Vigilancia_Sanitaria" type="xs:string"></xs:element>
        <xs:element name="Cnae" type="xs:string"></xs:element>
        <xs:element name="Mei" type="xs:string"></xs:element>
        <xs:element name="Area" type="xs:string"></xs:element>
        <xs:element name="Proprietario" type="xs:string"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== eduardoschwartz/GTI_v3C/GTI_WebCore/Models/ReportModels/Empresa_Detalhe.xml
<Empresa_Detalhe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="Empresa_Detalhe.xsd">
  <Codigo>123456</Codigo>
  <Razao_Social>Empresa de Teste</Razao_Social>
  <Cpf_Cnpj>50.387.655/0002-23</Cpf_Cnpj>
  <Inscricao_Estadual>12121</Inscricao_Estadual>
  <Endereco>Rua de Teste, 345 - 2ª Andar</Endereco>
  <Bairro>Nova Cidade</Bairro>
  <Cidade>Jaboticabal</Cidade>
  <UF>SP</UF>
  <Cep>15990450</Cep>
  <Data_Abertura>1980-03-23T10:20:15</Data_Abertura>
  <Data_Encerramento>1980-03-23T10:20:15</Data_Encerramento>
  <Atividade>Mecânico</Atividade>
  <Situacao>Ativa</Situacao>
  <Email>email@gti.com</Email>
  <Telefone>(16) 3333-2222</Telefone>
  <RegimeISS>Variavel</RegimeISS>
  <Taxa_Licenca>Sim</Taxa_Licenca>
  <Vigilancia_Sanitaria>Não</Vigilancia_Sanitaria>
  <Cnae>12345-6/34</Cnae>
  <Mei>Sim</Mei>
  <Area>1234,56 m²</Area>
  <Proprietario>Eduardo Schwartz</Proprietario>
</Empresa_Detalhe>
